project:
  type: website
  output-dir: docs

website:
  title: "ME"
  # site-url: https://placeholder.com
  description: "A website, by Michael"
  navbar:
    background: "#5375a9"
    right:
      - icon: github
        href: https://github.com/miellsworth
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/mellsworth.bsky.social
      - icon: mic
        href: https://cjsw.com/program/beat-salad

format:
  html:
    theme: flatly
    backgroundcolor: "#fbfae4"
    linkcolor: "#277272"
    # respect-user-color-scheme: true
